### ISSUE TITLE
##[error]Docker run failed with exit code 128

### ISSUE THREAD

**Issue by dreygur** [github-actions-x/commit#1]
The action fails to push the commit and shows the error: ##[error]Docker run failed with exit code 128

**Comment by perseus-me** [comment]
@dreygur Do you use v1 or master? I create new v1.1 with improvements.

**Comment by dreygur** [comment]
> 
> 
> @dreygur Do you use v1 or master? I create new v1.1 with improvements.

I used v1.0

**Comment by perseus-me** [comment]
Update to v2.0. I change input variable notation. Use dash instead underscore, e.g `github-token`
