### ISSUE TITLE
rebase broken?

### ISSUE THREAD

**Issue by nerdyscout** [github-actions-x/commit#22]
hi @rusnasonov 
thank you for providing this action. I've been using it a lot lately.

Unfortunately I struggle now to make it running here: https://github.com/nerdyscout/kicad-exports/actions/runs/352110762

Using another actions (kicad-exports itself) several files are generated. Some of these files are not needed and can be dumped, other files I need to push back into the repository. I guess `error: cannot rebase: You have unstaged changes.` does relate to my not needed files, but I don't understand why this is a problem here... and I need to rebase because several workflows run in parallel pushing into the same branch.

I am thankful for every hint!
regards

**Comment by moltar** [comment]
I suggest you add the following just before this action run:

```yml
      - name: Git dirty check
        run: git status -s
```

This should list all of the unstaged files.

There is probably a modification to one or more of your committed files during the build process.

**Comment by nerdyscout** [comment]
I did add the status check now.
Even if there are modifications I would have expected these are ignored. Otherwise It would not make sense to me to explicit define which files to commit when I still need to tell which modifications not to commit.

**Comment by nerdyscout** [comment]
I've "solved" this by using a complete new workflow.
